places = ['Paris', 'London', 'Amsterdam', 'Athenas', 'Berlin', 'Lisbon']
print(places)
print(sorted(places))
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)